Task 1
Hipodbehu/phoneshop pull request #1
Opened 2021-11-16 16:09 UTC by Hipodbehu

2021-11-17 20:48 UTC, ivanalexeenko requested changes

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/main/java/com/es/core/model/product/InvalidProductException.java
> +public class InvalidProductException extends RuntimeException {
Почему RuntimeException, а не Exception?

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/main/java/com/es/core/model/product/InvalidProductException.java
> +  }
Оставь только те конструкторы, которые тебе нужны для работы приложения

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +  private final ReadWriteLock readWriteLock = new ReentrantReadWriteLock();
Лучше визуально отделять public и private константы переносом

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +  private SimpleJdbcInsert simpleJdbcInsert;
Лучше визуально отделять константы, поля с аннотациями и обычные поля переносами строк

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +      phones = jdbcTemplate.query(SELECT_FROM_PHONES_OFFSET_LIMIT, new BeanPropertyRowMapper<>(Phone.class), offset, limit);
Разбивай длинные строчки (как и до этого)

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +    }
Сейчас нормально, но в будущем нужно будет вынести бизнес-логику в сервисы

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +  }
Не возвращай null из метода, когда можно вернуть Optional

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +    Long num = (Long) simpleJdbcInsert.executeAndReturnKey(source);
Непонятен смысл переменной, судя из названия num

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +    if (phone.getColors() != null && !phone.getColors().isEmpty()) {
Глянь использование CollectionUtils класса

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +      phone.getColors().forEach(color -> jdbcTemplate.update(INSERT_INTO_PHONE_2_COLOR, phone.getId(), color.getId()));
Используй batchUpdate вместо update в цикле

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/main/java/com/es/core/model/product/ProductNotFoundException.java
> +public class ProductNotFoundException extends RuntimeException {
RuntimeException vs Exception

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/main/java/com/es/core/model/product/ProductNotFoundException.java
> +}
Нужно ли столько конструкторов?

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/test/java/com/es/core/model/product/JdbcProductDaoTest.java
> +import static org.junit.Assert.*;
Нужно ли нам импортировать все статические методы из Assert? Или только их подмножество?

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/test/java/com/es/core/model/product/JdbcProductDaoTest.java
> +  private JdbcTemplate jdbcTemplate;
Отделяй визуально константы и ресурсы (переносы)

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/test/java/com/es/core/model/product/JdbcProductDaoTest.java
> +  public void tearDown() {
Название метода неконкретное: что мы "сносим"? Используй слова проще - remove, delete, clean

2021-11-17 20:48 UTC, ivanalexeenko commented on core/src/test/java/com/es/core/model/product/JdbcProductDaoTest.java
> +  }
Поработай над названиями тестовых методов. Они должны говорить конкретно, например - shouldThrowIllegalArgumentExceptionWhenSavePhoneEmptyId. Слово тест лишнее

2021-11-17 20:48 UTC, ivanalexeenko commented on web/src/main/webapp/WEB-INF/applicationContext.xml
> +    <context:property-placeholder location="/WEB-INF/conf/application.properties"></context:property-placeholder>
Лучше отделять теги разного смысла друг от друга (переносы строк)

2021-11-21 12:14 UTC, Hipodbehu commented on core/src/main/java/com/es/core/model/product/InvalidProductException.java
> +  }
Убрал лишние

2021-11-21 12:14 UTC, Hipodbehu commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +  private final ReadWriteLock readWriteLock = new ReentrantReadWriteLock();
Отделил

2021-11-21 12:14 UTC, Hipodbehu commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +    Long num = (Long) simpleJdbcInsert.executeAndReturnKey(source);
Изменил на id

2021-11-21 12:15 UTC, Hipodbehu commented on core/src/test/java/com/es/core/model/product/JdbcProductDaoTest.java
> +import static org.junit.Assert.*;
Исправил

2021-11-21 12:16 UTC, Hipodbehu commented on core/src/test/java/com/es/core/model/product/JdbcProductDaoTest.java
> +  public void tearDown() {
Изменил на clean

2021-11-21 12:16 UTC, Hipodbehu commented on core/src/test/java/com/es/core/model/product/JdbcProductDaoTest.java
> +  }
Поменял названия

2021-11-22 14:01 UTC, devjohnsmith1 requested changes

2021-11-22 14:01 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +import java.util.*;
Лишние импорты - проверяй перед коммитом

2021-11-22 14:01 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +    List<Long> phones = jdbcTemplate.queryForList(SELECT_PHONE_ID_BY_BRAND_AND_MODEL,
Переименуй параметр phones - кажется, что достаёшь именно телефоны, а оказывается, что их id

2021-11-22 14:01 UTC, devjohnsmith1 commented on core/src/test/java/com/es/core/model/product/JdbcProductDaoTest.java
> +  }
Непонятно, что тестируют эти два метода - брэнд задан, но в названии NoBrand, с моделью то же самое

2021-11-22 17:23 UTC, Hipodbehu commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +import java.util.*;
Все импорты нужны и используются

2021-11-22 17:24 UTC, Hipodbehu commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +    List<Long> phones = jdbcTemplate.queryForList(SELECT_PHONE_ID_BY_BRAND_AND_MODEL,
Переименовал на ids

2021-11-22 17:24 UTC, Hipodbehu commented on core/src/test/java/com/es/core/model/product/JdbcProductDaoTest.java
> +  }
Поменял названия

2021-11-23 07:30 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +import java.util.*;
Вряд ли все из import java.util.*

2021-11-23 07:30 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/product/JdbcProductDao.java
> +import java.util.*;
Вряд ли все из import java.util.*

2021-11-23 07:46 UTC, devjohnsmith1 approved these changes

2021-11-23 07:47 UTC, merged