Task 2.5: Implement ProductList page
Hipodbehu/phoneshop pull request #2
Opened 2021-11-25 13:00 UTC by Hipodbehu

2021-11-25 20:41 UTC, devjohnsmith1 requested changes

2021-11-25 20:41 UTC, devjohnsmith1 commented on core/pom.xml
> +  <modelVersion>4.0.0</modelVersion><build><plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId><configuration><source>8</source><target>8</target
Проверяй форматирование перед коммитом. Здесь теги не должны быть в одну строчку.

2021-11-25 20:41 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/cart/Cart.java
> +    return deliveryCost != null ? deliveryCost.equals(cart.deliveryCost) : cart.deliveryCost == null;
Используй Objects.equals

2021-11-25 20:41 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/cart/Cart.java
> +    return result;
используй Objects.hash - не стоит использовать magic numbers

2021-11-25 20:41 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/cart/CartItem.java
> +
Objects.hash + Objects.equals

2021-11-25 20:41 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/cart/CartService.java
> +  void remove(Long phoneId);
Не коммить код, который ты не менял - форматирования сбивают с толку

2021-11-25 20:41 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
>  }
Настрой форматирование в IDE (на него полагаться не стоит)

2021-11-25 20:41 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +    return jdbcTemplate.query("select * from phones offset " + offset + " limit " + limit, new BeanPropertyRowMapper(Phone.class));
Вынеси строчки в константы

2021-11-25 20:41 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/Phone.java
> +  }
Objects.hash + Objects.equals

2021-11-25 20:41 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/Phone.java
> +  }
Все эти форматирования ты осознанно сделал или они не нужны?

2021-11-28 14:56 UTC, Hipodbehu commented on core/pom.xml
> +  <modelVersion>4.0.0</modelVersion><build><plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId><configuration><source>8</source><target>8</target
Исправил

2021-11-28 14:56 UTC, Hipodbehu commented on core/src/main/java/com/es/core/cart/Cart.java
> +    return deliveryCost != null ? deliveryCost.equals(cart.deliveryCost) : cart.deliveryCost == null;
Поменял на Objects.equals

2021-11-28 14:56 UTC, Hipodbehu commented on core/src/main/java/com/es/core/cart/Cart.java
> +    return result;
Поменял

2021-11-28 14:56 UTC, Hipodbehu commented on core/src/main/java/com/es/core/cart/CartItem.java
> +
Исправил

2021-11-28 14:57 UTC, Hipodbehu commented on core/src/main/java/com/es/core/model/phone/Phone.java
> +  }
Исправил

2021-11-29 13:32 UTC, devjohnsmith1 requested changes

2021-11-29 13:32 UTC, devjohnsmith1 commented on web/src/main/java/com/es/phoneshop/web/controller/validation/QuantityInputWrapper.java
> +  private String quantity;
нужно будет переписать на валидацию числового значения quantity в следующем Code Review Point

2021-11-29 13:32 UTC, devjohnsmith1 commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
> +  private Integer checkPageNumber(String pageNumber, int countOfPages) {
Проверяй строчки на пустоту через StringUtils.isEmpty/StringUtils.isBlank. + Название методов "check" говорят о валидации - здесь мы не валидируем

2021-11-29 18:18 UTC, Hipodbehu commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
> +  private Integer checkPageNumber(String pageNumber, int countOfPages) {
Исправил

2021-11-30 06:13 UTC, devjohnsmith1 approved these changes

2021-11-30 10:43 UTC, merged