Task 3
Hipodbehu/phoneshop pull request #3
Opened 2021-12-02 14:32 UTC by Hipodbehu

2021-12-03 12:00 UTC, devjohnsmith1 requested changes

2021-12-03 12:00 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        }
Неочевидно, что метод update возвращает errors, судя по его семантике. Либо кидай эксепшн, либо передавай errors в сам метод update

2021-12-03 12:00 UTC, devjohnsmith1 commented on core/src/test/java/com/es/core/cart/HttpSessionCartServiceTest.java
> +public class HttpSessionCartServiceTest {
Никак не помечаем, как запускаются тесты?

2021-12-03 12:00 UTC, devjohnsmith1 commented on web/src/main/webapp/resources/js/addToCart.js
> +    // })
Удаляй ненужный код

2021-12-03 12:10 UTC, devjohnsmith1 commented on web/src/main/webapp/WEB-INF/pages/cart.jsp
> +                    <td>Action</td>
Выноси строчки из jsp в проперти файлы (ResourceBundles)

2021-12-06 10:19 UTC, Hipodbehu commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        }
Исправил

2021-12-06 10:19 UTC, Hipodbehu commented on web/src/main/webapp/resources/js/addToCart.js
> +    // })
Удалил

2021-12-07 12:24 UTC, Hipodbehu commented on web/src/main/webapp/WEB-INF/pages/cart.jsp
> +                    <td>Action</td>
Вынес

2021-12-07 12:26 UTC, devjohnsmith1 approved these changes

2021-12-07 16:05 UTC, merged