Tasks 2.8-2.9 Implemented OrderPage and OrderOverviewPage
Hipodbehu/phoneshop pull request #4
Opened 2021-12-09 14:14 UTC by Hipodbehu

2021-12-10 11:51 UTC, devjohnsmith1 requested changes

2021-12-10 11:51 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/order/JdbcOrderDao.java
> +      phone = phones.get(0);
Что если запрос вернёт пустой список?

2021-12-10 11:51 UTC, devjohnsmith1 commented on core/src/main/resources/db/schema.sql
> +                        UNIQUE (code)
Нужно это форматирование?

2021-12-10 11:51 UTC, devjohnsmith1 commented on core/src/main/resources/db/schema.sql
>  );
Форматирования?

2021-12-10 11:51 UTC, devjohnsmith1 commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        }
Можно ли поля вынести в форму и вынести код в валидатор?

2021-12-13 19:21 UTC, Hipodbehu commented on core/src/main/java/com/es/core/order/JdbcOrderDao.java
> +      phone = phones.get(0);
Исправил на Optional

2021-12-13 19:22 UTC, Hipodbehu commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        }
Изменил способ валидации

2021-12-14 17:27 UTC, devjohnsmith1 approved these changes

2021-12-15 10:38 UTC, merged